#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSV")]
public partial class mienDataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblDangKy(tblDangKy instance);
  partial void UpdatetblDangKy(tblDangKy instance);
  partial void DeletetblDangKy(tblDangKy instance);
  partial void InserttblPhanCong(tblPhanCong instance);
  partial void UpdatetblPhanCong(tblPhanCong instance);
  partial void DeletetblPhanCong(tblPhanCong instance);
  partial void InserttblGiaoVien(tblGiaoVien instance);
  partial void UpdatetblGiaoVien(tblGiaoVien instance);
  partial void DeletetblGiaoVien(tblGiaoVien instance);
  partial void InserttblHocVien(tblHocVien instance);
  partial void UpdatetblHocVien(tblHocVien instance);
  partial void DeletetblHocVien(tblHocVien instance);
  partial void InserttblKetQua(tblKetQua instance);
  partial void UpdatetblKetQua(tblKetQua instance);
  partial void DeletetblKetQua(tblKetQua instance);
  partial void InserttblMonHoc(tblMonHoc instance);
  partial void UpdatetblMonHoc(tblMonHoc instance);
  partial void DeletetblMonHoc(tblMonHoc instance);
  #endregion
	
	public mienDataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLSVConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public mienDataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public mienDataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public mienDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public mienDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblDangKy> tblDangKies
	{
		get
		{
			return this.GetTable<tblDangKy>();
		}
	}
	
	public System.Data.Linq.Table<tblPhanCong> tblPhanCongs
	{
		get
		{
			return this.GetTable<tblPhanCong>();
		}
	}
	
	public System.Data.Linq.Table<tblGiaoVien> tblGiaoViens
	{
		get
		{
			return this.GetTable<tblGiaoVien>();
		}
	}
	
	public System.Data.Linq.Table<tblHocVien> tblHocViens
	{
		get
		{
			return this.GetTable<tblHocVien>();
		}
	}
	
	public System.Data.Linq.Table<tblKetQua> tblKetQuas
	{
		get
		{
			return this.GetTable<tblKetQua>();
		}
	}
	
	public System.Data.Linq.Table<tblMonHoc> tblMonHocs
	{
		get
		{
			return this.GetTable<tblMonHoc>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDangKy")]
public partial class tblDangKy : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaHV;
	
	private string _MaMH;
	
	private System.Nullable<System.DateTime> _NgayKG;
	
	private System.Nullable<System.DateTime> _NgayKT;
	
	private string _GhiChu;
	
	private EntityRef<tblHocVien> _tblHocVien;
	
	private EntityRef<tblMonHoc> _tblMonHoc;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHVChanging(string value);
    partial void OnMaHVChanged();
    partial void OnMaMHChanging(string value);
    partial void OnMaMHChanged();
    partial void OnNgayKGChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKGChanged();
    partial void OnNgayKTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKTChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
	
	public tblDangKy()
	{
		this._tblHocVien = default(EntityRef<tblHocVien>);
		this._tblMonHoc = default(EntityRef<tblMonHoc>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaHV
	{
		get
		{
			return this._MaHV;
		}
		set
		{
			if ((this._MaHV != value))
			{
				if (this._tblHocVien.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaHVChanging(value);
				this.SendPropertyChanging();
				this._MaHV = value;
				this.SendPropertyChanged("MaHV");
				this.OnMaHVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaMH
	{
		get
		{
			return this._MaMH;
		}
		set
		{
			if ((this._MaMH != value))
			{
				if (this._tblMonHoc.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaMHChanging(value);
				this.SendPropertyChanging();
				this._MaMH = value;
				this.SendPropertyChanged("MaMH");
				this.OnMaMHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKG", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgayKG
	{
		get
		{
			return this._NgayKG;
		}
		set
		{
			if ((this._NgayKG != value))
			{
				this.OnNgayKGChanging(value);
				this.SendPropertyChanging();
				this._NgayKG = value;
				this.SendPropertyChanged("NgayKG");
				this.OnNgayKGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKT", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgayKT
	{
		get
		{
			return this._NgayKT;
		}
		set
		{
			if ((this._NgayKT != value))
			{
				this.OnNgayKTChanging(value);
				this.SendPropertyChanging();
				this._NgayKT = value;
				this.SendPropertyChanged("NgayKT");
				this.OnNgayKTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(150)")]
	public string GhiChu
	{
		get
		{
			return this._GhiChu;
		}
		set
		{
			if ((this._GhiChu != value))
			{
				this.OnGhiChuChanging(value);
				this.SendPropertyChanging();
				this._GhiChu = value;
				this.SendPropertyChanged("GhiChu");
				this.OnGhiChuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHocVien_tblDangKy", Storage="_tblHocVien", ThisKey="MaHV", OtherKey="MaHV", IsForeignKey=true)]
	public tblHocVien tblHocVien
	{
		get
		{
			return this._tblHocVien.Entity;
		}
		set
		{
			tblHocVien previousValue = this._tblHocVien.Entity;
			if (((previousValue != value) 
						|| (this._tblHocVien.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblHocVien.Entity = null;
					previousValue.tblDangKies.Remove(this);
				}
				this._tblHocVien.Entity = value;
				if ((value != null))
				{
					value.tblDangKies.Add(this);
					this._MaHV = value.MaHV;
				}
				else
				{
					this._MaHV = default(string);
				}
				this.SendPropertyChanged("tblHocVien");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMonHoc_tblDangKy", Storage="_tblMonHoc", ThisKey="MaMH", OtherKey="MaMH", IsForeignKey=true)]
	public tblMonHoc tblMonHoc
	{
		get
		{
			return this._tblMonHoc.Entity;
		}
		set
		{
			tblMonHoc previousValue = this._tblMonHoc.Entity;
			if (((previousValue != value) 
						|| (this._tblMonHoc.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblMonHoc.Entity = null;
					previousValue.tblDangKies.Remove(this);
				}
				this._tblMonHoc.Entity = value;
				if ((value != null))
				{
					value.tblDangKies.Add(this);
					this._MaMH = value.MaMH;
				}
				else
				{
					this._MaMH = default(string);
				}
				this.SendPropertyChanged("tblMonHoc");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhanCong")]
public partial class tblPhanCong : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaGV;
	
	private string _MaMH;
	
	private string _GhiChu;
	
	private EntityRef<tblGiaoVien> _tblGiaoVien;
	
	private EntityRef<tblMonHoc> _tblMonHoc;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVChanging(string value);
    partial void OnMaGVChanged();
    partial void OnMaMHChanging(string value);
    partial void OnMaMHChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
	
	public tblPhanCong()
	{
		this._tblGiaoVien = default(EntityRef<tblGiaoVien>);
		this._tblMonHoc = default(EntityRef<tblMonHoc>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaGV
	{
		get
		{
			return this._MaGV;
		}
		set
		{
			if ((this._MaGV != value))
			{
				if (this._tblGiaoVien.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaGVChanging(value);
				this.SendPropertyChanging();
				this._MaGV = value;
				this.SendPropertyChanged("MaGV");
				this.OnMaGVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaMH
	{
		get
		{
			return this._MaMH;
		}
		set
		{
			if ((this._MaMH != value))
			{
				if (this._tblMonHoc.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaMHChanging(value);
				this.SendPropertyChanging();
				this._MaMH = value;
				this.SendPropertyChanged("MaMH");
				this.OnMaMHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
	public string GhiChu
	{
		get
		{
			return this._GhiChu;
		}
		set
		{
			if ((this._GhiChu != value))
			{
				this.OnGhiChuChanging(value);
				this.SendPropertyChanging();
				this._GhiChu = value;
				this.SendPropertyChanged("GhiChu");
				this.OnGhiChuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGiaoVien_tblPhanCong", Storage="_tblGiaoVien", ThisKey="MaGV", OtherKey="MaGV", IsForeignKey=true)]
	public tblGiaoVien tblGiaoVien
	{
		get
		{
			return this._tblGiaoVien.Entity;
		}
		set
		{
			tblGiaoVien previousValue = this._tblGiaoVien.Entity;
			if (((previousValue != value) 
						|| (this._tblGiaoVien.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblGiaoVien.Entity = null;
					previousValue.tblPhanCongs.Remove(this);
				}
				this._tblGiaoVien.Entity = value;
				if ((value != null))
				{
					value.tblPhanCongs.Add(this);
					this._MaGV = value.MaGV;
				}
				else
				{
					this._MaGV = default(string);
				}
				this.SendPropertyChanged("tblGiaoVien");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMonHoc_tblPhanCong", Storage="_tblMonHoc", ThisKey="MaMH", OtherKey="MaMH", IsForeignKey=true)]
	public tblMonHoc tblMonHoc
	{
		get
		{
			return this._tblMonHoc.Entity;
		}
		set
		{
			tblMonHoc previousValue = this._tblMonHoc.Entity;
			if (((previousValue != value) 
						|| (this._tblMonHoc.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblMonHoc.Entity = null;
					previousValue.tblPhanCongs.Remove(this);
				}
				this._tblMonHoc.Entity = value;
				if ((value != null))
				{
					value.tblPhanCongs.Add(this);
					this._MaMH = value.MaMH;
				}
				else
				{
					this._MaMH = default(string);
				}
				this.SendPropertyChanged("tblMonHoc");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblGiaoVien")]
public partial class tblGiaoVien : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaGV;
	
	private string _HoGV;
	
	private string _TenGV;
	
	private string _GioiTinh;
	
	private string _DiaChi;
	
	private string _DienThoai;
	
	private EntitySet<tblPhanCong> _tblPhanCongs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVChanging(string value);
    partial void OnMaGVChanged();
    partial void OnHoGVChanging(string value);
    partial void OnHoGVChanged();
    partial void OnTenGVChanging(string value);
    partial void OnTenGVChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    #endregion
	
	public tblGiaoVien()
	{
		this._tblPhanCongs = new EntitySet<tblPhanCong>(new Action<tblPhanCong>(this.attach_tblPhanCongs), new Action<tblPhanCong>(this.detach_tblPhanCongs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaGV
	{
		get
		{
			return this._MaGV;
		}
		set
		{
			if ((this._MaGV != value))
			{
				this.OnMaGVChanging(value);
				this.SendPropertyChanging();
				this._MaGV = value;
				this.SendPropertyChanged("MaGV");
				this.OnMaGVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoGV", DbType="NVarChar(50)")]
	public string HoGV
	{
		get
		{
			return this._HoGV;
		}
		set
		{
			if ((this._HoGV != value))
			{
				this.OnHoGVChanging(value);
				this.SendPropertyChanging();
				this._HoGV = value;
				this.SendPropertyChanged("HoGV");
				this.OnHoGVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGV", DbType="NVarChar(50)")]
	public string TenGV
	{
		get
		{
			return this._TenGV;
		}
		set
		{
			if ((this._TenGV != value))
			{
				this.OnTenGVChanging(value);
				this.SendPropertyChanging();
				this._TenGV = value;
				this.SendPropertyChanged("TenGV");
				this.OnTenGVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5)")]
	public string GioiTinh
	{
		get
		{
			return this._GioiTinh;
		}
		set
		{
			if ((this._GioiTinh != value))
			{
				this.OnGioiTinhChanging(value);
				this.SendPropertyChanging();
				this._GioiTinh = value;
				this.SendPropertyChanged("GioiTinh");
				this.OnGioiTinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(150)")]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(20)")]
	public string DienThoai
	{
		get
		{
			return this._DienThoai;
		}
		set
		{
			if ((this._DienThoai != value))
			{
				this.OnDienThoaiChanging(value);
				this.SendPropertyChanging();
				this._DienThoai = value;
				this.SendPropertyChanged("DienThoai");
				this.OnDienThoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGiaoVien_tblPhanCong", Storage="_tblPhanCongs", ThisKey="MaGV", OtherKey="MaGV")]
	public EntitySet<tblPhanCong> tblPhanCongs
	{
		get
		{
			return this._tblPhanCongs;
		}
		set
		{
			this._tblPhanCongs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblPhanCongs(tblPhanCong entity)
	{
		this.SendPropertyChanging();
		entity.tblGiaoVien = this;
	}
	
	private void detach_tblPhanCongs(tblPhanCong entity)
	{
		this.SendPropertyChanging();
		entity.tblGiaoVien = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHocVien")]
public partial class tblHocVien : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaHV;
	
	private string _HoHV;
	
	private string _TenHV;
	
	private string _GioiTinh;
	
	private System.Nullable<System.DateTime> _NgaySinh;
	
	private string _NoiSinh;
	
	private string _DiaChi;
	
	private string _DienThoai;
	
	private EntitySet<tblDangKy> _tblDangKies;
	
	private EntitySet<tblKetQua> _tblKetQuas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHVChanging(string value);
    partial void OnMaHVChanged();
    partial void OnHoHVChanging(string value);
    partial void OnHoHVChanged();
    partial void OnTenHVChanging(string value);
    partial void OnTenHVChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnNoiSinhChanging(string value);
    partial void OnNoiSinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    #endregion
	
	public tblHocVien()
	{
		this._tblDangKies = new EntitySet<tblDangKy>(new Action<tblDangKy>(this.attach_tblDangKies), new Action<tblDangKy>(this.detach_tblDangKies));
		this._tblKetQuas = new EntitySet<tblKetQua>(new Action<tblKetQua>(this.attach_tblKetQuas), new Action<tblKetQua>(this.detach_tblKetQuas));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaHV
	{
		get
		{
			return this._MaHV;
		}
		set
		{
			if ((this._MaHV != value))
			{
				this.OnMaHVChanging(value);
				this.SendPropertyChanging();
				this._MaHV = value;
				this.SendPropertyChanged("MaHV");
				this.OnMaHVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoHV", DbType="NVarChar(50)")]
	public string HoHV
	{
		get
		{
			return this._HoHV;
		}
		set
		{
			if ((this._HoHV != value))
			{
				this.OnHoHVChanging(value);
				this.SendPropertyChanging();
				this._HoHV = value;
				this.SendPropertyChanged("HoHV");
				this.OnHoHVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHV", DbType="NVarChar(50)")]
	public string TenHV
	{
		get
		{
			return this._TenHV;
		}
		set
		{
			if ((this._TenHV != value))
			{
				this.OnTenHVChanging(value);
				this.SendPropertyChanging();
				this._TenHV = value;
				this.SendPropertyChanged("TenHV");
				this.OnTenHVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5)")]
	public string GioiTinh
	{
		get
		{
			return this._GioiTinh;
		}
		set
		{
			if ((this._GioiTinh != value))
			{
				this.OnGioiTinhChanging(value);
				this.SendPropertyChanging();
				this._GioiTinh = value;
				this.SendPropertyChanged("GioiTinh");
				this.OnGioiTinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
	public System.Nullable<System.DateTime> NgaySinh
	{
		get
		{
			return this._NgaySinh;
		}
		set
		{
			if ((this._NgaySinh != value))
			{
				this.OnNgaySinhChanging(value);
				this.SendPropertyChanging();
				this._NgaySinh = value;
				this.SendPropertyChanged("NgaySinh");
				this.OnNgaySinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(150)")]
	public string NoiSinh
	{
		get
		{
			return this._NoiSinh;
		}
		set
		{
			if ((this._NoiSinh != value))
			{
				this.OnNoiSinhChanging(value);
				this.SendPropertyChanging();
				this._NoiSinh = value;
				this.SendPropertyChanged("NoiSinh");
				this.OnNoiSinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(150)")]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(20)")]
	public string DienThoai
	{
		get
		{
			return this._DienThoai;
		}
		set
		{
			if ((this._DienThoai != value))
			{
				this.OnDienThoaiChanging(value);
				this.SendPropertyChanging();
				this._DienThoai = value;
				this.SendPropertyChanged("DienThoai");
				this.OnDienThoaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHocVien_tblDangKy", Storage="_tblDangKies", ThisKey="MaHV", OtherKey="MaHV")]
	public EntitySet<tblDangKy> tblDangKies
	{
		get
		{
			return this._tblDangKies;
		}
		set
		{
			this._tblDangKies.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHocVien_tblKetQua", Storage="_tblKetQuas", ThisKey="MaHV", OtherKey="MaHV")]
	public EntitySet<tblKetQua> tblKetQuas
	{
		get
		{
			return this._tblKetQuas;
		}
		set
		{
			this._tblKetQuas.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblDangKies(tblDangKy entity)
	{
		this.SendPropertyChanging();
		entity.tblHocVien = this;
	}
	
	private void detach_tblDangKies(tblDangKy entity)
	{
		this.SendPropertyChanging();
		entity.tblHocVien = null;
	}
	
	private void attach_tblKetQuas(tblKetQua entity)
	{
		this.SendPropertyChanging();
		entity.tblHocVien = this;
	}
	
	private void detach_tblKetQuas(tblKetQua entity)
	{
		this.SendPropertyChanging();
		entity.tblHocVien = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKetQua")]
public partial class tblKetQua : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaHV;
	
	private string _MaMH;
	
	private System.Nullable<double> _Diem;
	
	private EntityRef<tblHocVien> _tblHocVien;
	
	private EntityRef<tblMonHoc> _tblMonHoc;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHVChanging(string value);
    partial void OnMaHVChanged();
    partial void OnMaMHChanging(string value);
    partial void OnMaMHChanged();
    partial void OnDiemChanging(System.Nullable<double> value);
    partial void OnDiemChanged();
    #endregion
	
	public tblKetQua()
	{
		this._tblHocVien = default(EntityRef<tblHocVien>);
		this._tblMonHoc = default(EntityRef<tblMonHoc>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaHV
	{
		get
		{
			return this._MaHV;
		}
		set
		{
			if ((this._MaHV != value))
			{
				if (this._tblHocVien.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaHVChanging(value);
				this.SendPropertyChanging();
				this._MaHV = value;
				this.SendPropertyChanged("MaHV");
				this.OnMaHVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaMH
	{
		get
		{
			return this._MaMH;
		}
		set
		{
			if ((this._MaMH != value))
			{
				if (this._tblMonHoc.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMaMHChanging(value);
				this.SendPropertyChanging();
				this._MaMH = value;
				this.SendPropertyChanged("MaMH");
				this.OnMaMHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diem", DbType="Float")]
	public System.Nullable<double> Diem
	{
		get
		{
			return this._Diem;
		}
		set
		{
			if ((this._Diem != value))
			{
				this.OnDiemChanging(value);
				this.SendPropertyChanging();
				this._Diem = value;
				this.SendPropertyChanged("Diem");
				this.OnDiemChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHocVien_tblKetQua", Storage="_tblHocVien", ThisKey="MaHV", OtherKey="MaHV", IsForeignKey=true)]
	public tblHocVien tblHocVien
	{
		get
		{
			return this._tblHocVien.Entity;
		}
		set
		{
			tblHocVien previousValue = this._tblHocVien.Entity;
			if (((previousValue != value) 
						|| (this._tblHocVien.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblHocVien.Entity = null;
					previousValue.tblKetQuas.Remove(this);
				}
				this._tblHocVien.Entity = value;
				if ((value != null))
				{
					value.tblKetQuas.Add(this);
					this._MaHV = value.MaHV;
				}
				else
				{
					this._MaHV = default(string);
				}
				this.SendPropertyChanged("tblHocVien");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMonHoc_tblKetQua", Storage="_tblMonHoc", ThisKey="MaMH", OtherKey="MaMH", IsForeignKey=true)]
	public tblMonHoc tblMonHoc
	{
		get
		{
			return this._tblMonHoc.Entity;
		}
		set
		{
			tblMonHoc previousValue = this._tblMonHoc.Entity;
			if (((previousValue != value) 
						|| (this._tblMonHoc.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblMonHoc.Entity = null;
					previousValue.tblKetQuas.Remove(this);
				}
				this._tblMonHoc.Entity = value;
				if ((value != null))
				{
					value.tblKetQuas.Add(this);
					this._MaMH = value.MaMH;
				}
				else
				{
					this._MaMH = default(string);
				}
				this.SendPropertyChanged("tblMonHoc");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMonHoc")]
public partial class tblMonHoc : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaMH;
	
	private string _TenMH;
	
	private System.Nullable<int> _SoTiet;
	
	private System.Nullable<decimal> _HocPhi;
	
	private EntitySet<tblDangKy> _tblDangKies;
	
	private EntitySet<tblPhanCong> _tblPhanCongs;
	
	private EntitySet<tblKetQua> _tblKetQuas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMHChanging(string value);
    partial void OnMaMHChanged();
    partial void OnTenMHChanging(string value);
    partial void OnTenMHChanged();
    partial void OnSoTietChanging(System.Nullable<int> value);
    partial void OnSoTietChanged();
    partial void OnHocPhiChanging(System.Nullable<decimal> value);
    partial void OnHocPhiChanged();
    #endregion
	
	public tblMonHoc()
	{
		this._tblDangKies = new EntitySet<tblDangKy>(new Action<tblDangKy>(this.attach_tblDangKies), new Action<tblDangKy>(this.detach_tblDangKies));
		this._tblPhanCongs = new EntitySet<tblPhanCong>(new Action<tblPhanCong>(this.attach_tblPhanCongs), new Action<tblPhanCong>(this.detach_tblPhanCongs));
		this._tblKetQuas = new EntitySet<tblKetQua>(new Action<tblKetQua>(this.attach_tblKetQuas), new Action<tblKetQua>(this.detach_tblKetQuas));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaMH
	{
		get
		{
			return this._MaMH;
		}
		set
		{
			if ((this._MaMH != value))
			{
				this.OnMaMHChanging(value);
				this.SendPropertyChanging();
				this._MaMH = value;
				this.SendPropertyChanged("MaMH");
				this.OnMaMHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMH", DbType="NVarChar(150)")]
	public string TenMH
	{
		get
		{
			return this._TenMH;
		}
		set
		{
			if ((this._TenMH != value))
			{
				this.OnTenMHChanging(value);
				this.SendPropertyChanging();
				this._TenMH = value;
				this.SendPropertyChanged("TenMH");
				this.OnTenMHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTiet", DbType="Int")]
	public System.Nullable<int> SoTiet
	{
		get
		{
			return this._SoTiet;
		}
		set
		{
			if ((this._SoTiet != value))
			{
				this.OnSoTietChanging(value);
				this.SendPropertyChanging();
				this._SoTiet = value;
				this.SendPropertyChanged("SoTiet");
				this.OnSoTietChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocPhi", DbType="Money")]
	public System.Nullable<decimal> HocPhi
	{
		get
		{
			return this._HocPhi;
		}
		set
		{
			if ((this._HocPhi != value))
			{
				this.OnHocPhiChanging(value);
				this.SendPropertyChanging();
				this._HocPhi = value;
				this.SendPropertyChanged("HocPhi");
				this.OnHocPhiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMonHoc_tblDangKy", Storage="_tblDangKies", ThisKey="MaMH", OtherKey="MaMH")]
	public EntitySet<tblDangKy> tblDangKies
	{
		get
		{
			return this._tblDangKies;
		}
		set
		{
			this._tblDangKies.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMonHoc_tblPhanCong", Storage="_tblPhanCongs", ThisKey="MaMH", OtherKey="MaMH")]
	public EntitySet<tblPhanCong> tblPhanCongs
	{
		get
		{
			return this._tblPhanCongs;
		}
		set
		{
			this._tblPhanCongs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMonHoc_tblKetQua", Storage="_tblKetQuas", ThisKey="MaMH", OtherKey="MaMH")]
	public EntitySet<tblKetQua> tblKetQuas
	{
		get
		{
			return this._tblKetQuas;
		}
		set
		{
			this._tblKetQuas.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblDangKies(tblDangKy entity)
	{
		this.SendPropertyChanging();
		entity.tblMonHoc = this;
	}
	
	private void detach_tblDangKies(tblDangKy entity)
	{
		this.SendPropertyChanging();
		entity.tblMonHoc = null;
	}
	
	private void attach_tblPhanCongs(tblPhanCong entity)
	{
		this.SendPropertyChanging();
		entity.tblMonHoc = this;
	}
	
	private void detach_tblPhanCongs(tblPhanCong entity)
	{
		this.SendPropertyChanging();
		entity.tblMonHoc = null;
	}
	
	private void attach_tblKetQuas(tblKetQua entity)
	{
		this.SendPropertyChanging();
		entity.tblMonHoc = this;
	}
	
	private void detach_tblKetQuas(tblKetQua entity)
	{
		this.SendPropertyChanging();
		entity.tblMonHoc = null;
	}
}
#pragma warning restore 1591
